name: football
description: A very shitty replica of the very first Facebook Messenger game, Football where user tries to keep the football on the screen by tapping on it and the ball bounces on either sides respective to the user's touch 

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  shared_preferences: ^0.5.2
  flutter_launcher_icons: "^0.7.0"

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "asset/football.png"

flutter:
  uses-material-design: true
  assets:
   - asset/football.png